# Generated by Django 5.0.3 on 2024-03-22 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "permissions": [
                    ("can_view_post", "Can view post"),
                    ("can_like_post", "Can like post"),
                    ("can_dislike_post", "Can dislike post"),
                    ("can_comment_post", "Can comment post"),
                ]
            },
        ),
    ]
