# Generated by Django 5.0.3 on 2024-03-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0002_alter_post_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={},
        ),
    ]
