# Generated by Django 5.0.3 on 2024-03-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                default="default.jpg", upload_to="profile_pictures"
            ),
        ),
    ]
