# Generated by Django 5.0.3 on 2024-03-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                default="profile_pictures/default.jpg", upload_to="profile_pictures"
            ),
        ),
    ]
