# Generated by Django 5.0.3 on 2024-03-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("main", "0009_user_bio"),
        ("socialmedia", "0003_alter_post_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="CUser",
        ),
    ]
