# Generated by Django 5.0.3 on 2024-03-23 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("main", "0010_rename_user_cuser"),
        ("socialmedia", "0005_comment_dislikes_comment_likes_post_dislikes_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CUser",
            new_name="User",
        ),
    ]
