# Generated by Django 5.0.3 on 2024-03-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_rename_cuser_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="uploads/profile_pictures/default.jpg",
                null=True,
                upload_to="uploads/profile_pictures",
            ),
        ),
        migrations.DeleteModel(
            name="virtual_class",
        ),
    ]
