# Generated by Django 5.0.3 on 2024-04-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_user_profile_picture_delete_virtual_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="uploads/resumes"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(default="student", max_length=20),
        ),
    ]
